# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: maintenance_info.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'maintenance_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16maintenance_info.proto\"\xae\x02\n\x0fMaintenanceInfo\x12\x13\n\x0bmarket_type\x18\x01 \x01(\x05\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x16\n\x0e\x62undle_version\x18\x03 \x01(\t\x12\x18\n\x10is_bundle_update\x18\x04 \x01(\x08\x12\x18\n\x10maintenance_type\x18\x05 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\x12\x13\n\x0bregion_list\x18\x07 \x01(\t\x12\x0f\n\x07use_dsa\x18\x08 \x01(\x08\x12\x17\n\x0fmaintenance_url\x18\t \x01(\t\x12\x1b\n\x13use_maintenance_url\x18\n \x01(\x08\x12\x14\n\x0c\x64ownload_url\x18\x0b \x01(\t\x12\x0e\n\x06notice\x18\x0c \x01(\t\x12\x19\n\x11\x62undle_version_sd\x18\r \x01(\t\"\x90\x01\n\x16MaintenanceInfoRequest\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\x13\n\x0bmarket_type\x18\x02 \x01(\x05\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x16\n\x0e\x62undle_version\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x05 \x01(\t\x12\x15\n\rlanguage_type\x18\x06 \x01(\x05\"\x86\x01\n\x17MaintenanceInfoResponse\x12%\n\x0bmarket_info\x18\x01 \x01(\x0b\x32\x10.MaintenanceInfo\x12\x1b\n\x13server_connect_info\x18\x02 \x01(\t\x12\x14\n\x0c\x63onnect_type\x18\x03 \x01(\x05\x12\x11\n\tuser_type\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maintenance_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAINTENANCEINFO']._serialized_start=27
  _globals['_MAINTENANCEINFO']._serialized_end=329
  _globals['_MAINTENANCEINFOREQUEST']._serialized_start=332
  _globals['_MAINTENANCEINFOREQUEST']._serialized_end=476
  _globals['_MAINTENANCEINFORESPONSE']._serialized_start=479
  _globals['_MAINTENANCEINFORESPONSE']._serialized_end=613
# @@protoc_insertion_point(module_scope)
